<a href="https://colab.research.google.com/github/linyongcheng/ai/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [19]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [20]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [25]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
ar2.shape

(2, 3)

In [31]:
import numpy as np

a=np.array([[0,1],[2,3]])

a.reshape(1,4)
a.reshape(4,1)

print(a)


[[0 1]
 [2 3]]


In [36]:
b = a.reshape(1,4)
b
#b.shape

array([[0, 1, 2, 3]])

In [33]:
c = a.reshape(4,1)
c.shape

(4, 1)

In [38]:
import numpy as np
x= np.arange(2,10).reshape(2,4)
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [39]:
import numpy as np
x= np.arange(24).reshape(4,3,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [41]:
np.arange(24).reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [43]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])